### PR TITLE
Update the enterprise template for 3.3.0

### PR DESCRIPTION
**Pull request by mwringe**

### CODE REVIEW

**Comment by mwringe** [comment]
[test]

**Comment by jcantrill** [comment]
@danmcp is it possible to enable this without standing up another jenkins job?

**Comment by danmcp** [comment]
@jcantrill You don't need another job.  But the existing job needs to support the different branches which I doubt it does now.  The things you need are:
- Handling checking out and syncing the right branch
- Having a base image for each branch to handle the different prereqs for the branch (Ex: docker and golang versions and everything else you rely on besides your code in the branch) or handling updating the prereqs in the instance after it's started

@stevekuznetsov FYI

**Comment by danmcp** [comment]
@sdodson I can or @jcantrill can.  Just give me the go ahead.

**Comment by mwringe** [comment]
@danmcp this should be good to go for 3.3.0, please merge when you have the chance. Thanks.

**Pull request merged**
