### PR TITLE
Move to Metrics 0.23.2.Final

### PR DESCRIPTION
**Pull request by jshaughn**
- Update cache declarations to match new version.

@mwringe Please review.

### CODE REVIEW

**Comment by mwringe** [comment]
LGTM

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
Oh, wait, nope, this is not sufficient. We need other changes to be applied for 0.23.2 that are not in this PR.

**Comment by jshaughn** [comment]
>  We need other changes...

@mwringe Let me know what I can do to update the PR. I'm not sure what else is needed.

**Comment by mwringe** [comment]
@jshaughn we just need a section added to https://github.com/openshift/origin-metrics/blob/master/deployer/templates/hawkular-metrics.yaml#L84 to add the following:

-Dhawkular.metrics.admin-tenant=_hawkular_admin

**Comment by mwringe** [comment]
@jshaughn awesome, thanks

LGTM

**Comment by mwringe** [comment]
[merge]

**Pull request merged**
