### PR TITLE
Documentation on how to enable Alerts management for a Service Account

### PR DESCRIPTION
**Pull request by simon3z**
cc @mwringe

### CODE REVIEW

**Comment by mwringe** [comment]
I don't know if I really see the point in adding this. A service account is just another 'user' type

**Comment by simon3z** [comment]
> I don't know if I really see the point in adding this. A service account is just another 'user' type

@mwringe then we may have to update the current documentation altogether because with `add-role-to-user` (documented now) it's not working, as it is a cluster role (requiring `add-cluster-role-to-user`).

**Comment by mwringe** [comment]
add-role-to-user grants permission for the current project only
add-cluster-role-to-user grants permissions across all projects

**Comment by mwringe** [comment]
What project/tenant are you trying to use this with which is not working?

**Comment by simon3z** [comment]
> What project/tenant are you trying to use this with which is not working?

@mwringe the exception is `_system` which of course requires the cluster-wide role.

**Comment by simon3z** [comment]
Ping @mwringe

**Comment by mwringe** [comment]
Pong. Unless you can explain why exactly this is needed, I will most likely close this issue. I don't exactly see the value in adding in these changes.

**Comment by simon3z** [comment]
> Pong. Unless you can explain why exactly this is needed, I will most likely close this issue. I don't exactly see the value in adding in these changes.

@mwringe it was not clear that you needed more information.

Given that:
```
# oadm help policy add-role-to-user
Add a role to users or serviceaccounts for the current project
```

how do you assign the role to a user/serviceaccount that should administer the alerts on the `_system` tenant? (the one that contains metrics about nodes, etc.) What project would you use?

Also, a management system wants to be able to manage the alerts across the cluster (no need to be added specifically in each project), so I think it should be documented how to do that.

**Comment by mwringe** [comment]
we may need to rewrite part of this docs here to make things more clear. But I do not think its the responsibility of the origin-metrics to explain how the policy mechanism in OpenShift works.

> how do you assign the role to a user/serviceaccount that should administer the alerts on the _system tenant? (the one that contains metrics about nodes, etc.) What project would you use?

Any tenant in Hawkular Metrics which start with an '_' is a special tenant and should not be used by normal users. It is something which exists outside of a project since it is collecting things at the node level and not the project level.

This is touched upon in the docs under the tenants and authorization section:

"There is one special _system tenant in Hawkular metrics which corresponds to system or node level metrics. This is where things like the cpu usage of the node would be stored."

"For the _system tenant, the user requesting to read from this tenant must have cluster-reader permission."

We may need to explain this better in the docs.

**Comment by mwringe** [comment]
Lets just merge this in for now. We probably need to update the docs here soon anyways to make a lot of things more clear.

**Comment by mwringe** [comment]
[merge]

**Pull request merged**
