### PR TITLE
Do not delete local image prior to hack/release.sh

### PR DESCRIPTION
**Pull request by smarterclayton**
It isn't necessary

### CODE REVIEW

**Comment by mwringe** [comment]
@jcantrill is there a particular reason why we remove images here? Just to make sure I am not missing something before we merge this PR?

**Comment by jcantrill** [comment]
@mwringe The only think I can think of is to ensure we get latest and don't have stale base images.  I don't really know; I don't remember adding this bit in.

It otherwise LGTM

**Comment by mwringe** [comment]
[merge]

**Comment by jcantrill** [comment]
@smarterclayton  does this need to be cherry-picked back to 1.5?

**Comment by smarterclayton** [comment]
Yes

**Comment by smarterclayton** [comment]
This was copied from origin release.sh, but it's not necessary on latest docker.

**Pull request merged**
