### PR TITLE
Deployer: make secret optional.

### PR DESCRIPTION
**Pull request by bbguimaraes**

### CODE REVIEW

**Comment by bbguimaraes** [comment]
@mwringe: PTAL, will start working on the docs this afternoon.

**Comment by bbguimaraes** [comment]
Documentation was way less work than I thought =)

The OSE docs still need to be updated, but it's probably easier to do the
secret and configmap update in one go.

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
Does this pass the full test suite? Are there any extra tests we should be adding?

**Comment by mwringe** [comment]
Actually, I think we need to get the full test suite running again. I am working to getting it back to functioning

**Comment by mwringe** [comment]
With the new ansible work, this PR is obsolete.

**Pull request closed without merging**
