### PR TITLE
Add in option to specify additional Heapster sinks to use.

### PR DESCRIPTION
**Pull request by mwringe**

### CODE REVIEW

**Comment by mwringe** [comment]
[test]

**Comment by jdnieto** [comment]
How can it be merged?

**Comment by mwringe** [comment]
@jcantrill a lot of our PR were on hold due to the ansible work (which took way longer than expected). How do you want to handle these PRs now?

**Comment by jcantrill** [comment]
@mwringe  You can merge the work since we are still supporting oc cluster up with the deployer, but I suspect this work is not relevent to that.  We should:
* direct people to submit changes against https://github.com/openshift/openshift-ansible/roles/openshit_metrics
* update our README in this repo to identify the deployer is depreciated in favor of ansible

**Pull request closed without merging**
