### PR TITLE
Set a Heapster user to not default to root.

### PR DESCRIPTION
**Pull request by mwringe**

### CODE REVIEW

**Comment by bbguimaraes** [comment]
Won't openshift make it run with an [arbitrary uid][use_uid] anyway?  Or am I
missing the purpose here?

Possibly a typo on `useradd`, should be uid 1000.

[use_uid]: https://docs.openshift.org/latest/creating_images/guidelines.html#use-uid

**Comment by mwringe** [comment]
> Won't openshift make it run with an arbitrary uid anyway? Or am I
missing the purpose here?

That is not exactly true. By default the SCC runAsUser is set to 'MustRunAsRange' which does have act in this manner.

But an admin can set the runAsUser to 'MustRunAsNonRoot', which will try and run the pod as the user specified in the dockerfile or in the pod configuration. If no user is specified, the default ends up being root, which is forbidden when using 'MustRunAsNonRoot'.

The PR gets around this issue by specifying a uid in the docker file. This means the uid will no longer be defaulted to root and it will work with the different 'runAsUser' options.

See https://bugzilla.redhat.com/show_bug.cgi?id=1393103

> Possibly a typo on useradd, should be uid 1000.

yeah, it should be 1000. Thanks for catching that. Although it actually doesn't matter, it can be anything as long as its not root :)

**Comment by mwringe** [comment]
Fixed the typo.

@bbguimaraes is there anything else? or can we merge this?

**Comment by bbguimaraes** [comment]
> That is not exactly true. By default the SCC runAsUser is set to
> 'MustRunAsRange' which does have act in this manner.

Ah, I see.  I was referring to the usual case.  I'm not sure I see the
advantage of using `MustRunAsNonRoot` and relying on the user specified on the
dockerfile, instead of the default for the `restricted` scc.  And as you
commented on the issue, assigning an explicit uid to the pod would be enough in
this case.

But it's good to have our image as non-root by default anyway.  LGTM.

**Comment by mwringe** [comment]
[merge]

**Pull request merged**
