### PR TITLE
Fixes for ci_test_every_pr.sh

### PR DESCRIPTION
**Pull request by bbguimaraes**
Fixes wrong build status reported [here]
(https://ci.openshift.redhat.com/jenkins/job/test-origin-metrics/37/).

### CODE REVIEW

**Comment by bbguimaraes** [comment]
[test]

**Comment by sosiouxme** [comment]
LGTM however now you're apparently running into test errors, looks like upstream test libs moved:

```
./ci_test_every_pr.sh: line 40: /data/src/github.com/openshift/origin/hack/text.sh: No such file or directory
```

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
LGTM, can you please squash the commits into 1 and remove the PR for https://github.com/openshift/origin-metrics/pull/164? We can merge that one separately after this issue is resolved.

**Comment by bbguimaraes** [comment]
@mwringe: squashed.

> LGTM, can you please [...] remove the PR for #164? We can merge that one
> separately after this issue is resolved.

The problem is that change is also necessary for the tests to run, removing it
will cause the test to fail.  I'd suggest just closing that other PR after this
one is in.

**Comment by mwringe** [comment]
[MERGE]

**Pull request merged**
