### PR TITLE
Timeout configuration option for Hawkular Metrics and Heapster

### PR DESCRIPTION
**Pull request by mwringe**

### CODE REVIEW

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
[merge]

**Comment by bbguimaraes** [comment]
Any reason why the default timeout is 300 on the heapster/hawkular-metrics
templates but 500 on all other places?

**Comment by mwringe** [comment]
Fix, I just updated them to 500 everywhere. Thanks for catching this.

**Pull request merged**
