### PR TITLE
Support configmap for cassandra config files

### PR DESCRIPTION
**Pull request by rubenvp8510**
WIP, do not merge yet. need to test.

### CODE REVIEW

**Comment by rubenvp8510** [comment]
@jsanda Could you please review when you get a chance?

Thanks

**Comment by jsanda** [comment]
I envision being able to store the contents of cassandra.yaml, logback.xml, and jvm.options in a ConfigMap. I do not anticipate being able to store cassandra-env.sh in the ConfigMap since it is a shell script that is **not** limited to structured data like key/value pairs.

I think that there is going to be some work in refactoring cassandra-docker.sh. It sets a number of properties in cassandra.yaml based on environment variables. I think that logic can and should change.

**Comment by rubenvp8510** [comment]
Haa, you're right, we should not be able to edit the cassandra-env.sh script. I will remove that script and will do some refactoring on it. I think is ok for cassandra.yaml, logback.xml, and jvm.options to be stored in the ConfigMap. IMHO.

**Comment by rubenvp8510** [comment]
@jsanda I forget to update this, it has been a long time since the last comment, not sure if this PR is still relevant. I removed the bash script from the config map.

As we discussed some time ago, I don't think we can replace the logic of the getting some variables from env vars. This is due to the fact that some of them are "dynamic", like the hostname and others.. we need to get them at runtime (when the pod starts). So we cannot have it fixed in a file.

**Pull request closed without merging**
