### PR TITLE
Set a default value if the STARTUP_TIMEOUT is not set.

### PR DESCRIPTION
**Pull request by mwringe**

### CODE REVIEW

**Comment by mwringe** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1395267

**Comment by jcantrill** [comment]
only question... why is timeout removed from the script?  is it no longer passed via a switch?   otherwise LGTM

**Comment by mwringe** [comment]
@jcantrill: Thanks.
We have bumped up the default value, so having the timeout specified in the script is no longer needed since the default is more than enough now.

**Comment by mwringe** [comment]
[merge]

**Pull request merged**
