### PR TITLE
Add system-only annotation to hawkular-metrics-admin

### PR DESCRIPTION
**Pull request by enj**
https://bugzilla.redhat.com/show_bug.cgi?id=1436620

cc @jwforres @benjaminapetersen

### CODE REVIEW

**Comment by enj** [comment]
[test]

**Comment by jcantrill** [comment]
@enj All Post 3.5 work has moved to https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_metrics.  This change will need to be applied to a template in ansible though I do not find this ClusterRole in the code base.  @mwringe did we miss something in the translation

**Comment by enj** [comment]
Ah OK, I have already opened https://github.com/openshift/openshift-ansible/pull/3783

Do I need to change it anywhere else?  Feel free to close this PR if it is unnecessary.

**Comment by jcantrill** [comment]
I'll allow you to close it unless it needs to be merged into some earlier release and needs to be moved through the process their

**Comment by enj** [comment]
> I'll allow you to close it unless it needs to be merged into some earlier release and needs to be moved through the process their

@jwforres I am assuming that is not the case here so I will go ahead and close this.

**Pull request closed without merging**
