### PR TITLE
Add comment about how to run with your own Hawkular Metrics ear

### PR DESCRIPTION
**Pull request by mwringe**

### CODE REVIEW

**Comment by mwringe** [comment]
[merge]

**Comment by jsanda** [comment]
Hopefully we can come up with something better than this. It is a bit error prone with having to uncomment/comment the line for coping the EAR file.

**Comment by mwringe** [comment]
What kind of option do you want? This should only be done in situations where you need to test a custom ear for testing purposes and its done to make things a bit easier for developers.

**Comment by jsanda** [comment]
Having to comment/uncomment the Dockerfile and manually copy the EAR file is error prone. For starters I think we need to make the maven repo configurable. This would allow me to build my working branch in hawkular-metrics, install artifacts into local maven repo, and then deploy those uncommitted changes into my local openshift cluster. This would also allow me to do the same with a remote branch. We should have similar functionality for heapster and cassandra as well.

**Pull request closed without merging**
