### PR TITLE
Update Cassandra to 3.0.9

### PR DESCRIPTION
**Pull request by mwringe**
The updates to cassandra-env.sh.template and cassandra.yaml.template are due to the differences in these files between the Cassandra versions

### CODE REVIEW

**Comment by mwringe** [comment]
[test]

**Comment by jcantrill** [comment]
@mwringe is this work to resolve https://trello.com/c/IZfjcSSI   Is it more then an R&D task?

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
@jsanda can you take a quick look at this and determine if the scripts we are using make sense to you?

Basically:
If the major.minor version of the last install is less than the major.minor version of the current install, then we run updatesstables

If the major.minor of the last install is greate than that of the current install, then we throw an error

If the majoar.minor version is the same, we don't do anything

**Comment by jsanda** [comment]
I think the changes look good. I do have one question though. Could the `.cassandra.version` file ever get deleted? If so, won't the scripts break?

**Comment by mwringe** [comment]
@jsanda yes, it relies on the .cassandra.version file, and if someone deletes that it could cause our scripts to not function properly. The same could be said for deleting files within the data directory of Cassandra. Or running a command in cqlsh that they shouldn't. I don't think we can really prevent someone from modifying the files on disk.

So if someone starts to delete or modify the .cassandra.version file, then our scripts could run 'nodetool upgradesstables' at the wrong time or fail to run when they should.

From my understanding, running 'nodetool upgradesstables' when its not actually needed is benign. So if someone deletes it, it just means that 'nodetool upgradesstables' will be run the next time the server is started, which shouldn't cause a problem.

If someone modifies the .cassandra.version to try and trick the scripts into thinking its running another version, then 'nodetool upgradesstables' might not get run when an update occurs. Not running 'nodetool upgradesstables' after an upgrade will cause some performance degradation, but I don't know if it will cause a catastrophic failure. It looks like worst case, the person will have to manually run the command to get things back into a working situation.

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
[merge]

**Pull request merged**
