### PR TITLE
Enable full test suite when performing a pr.

### PR DESCRIPTION
**Pull request by mwringe**

### CODE REVIEW

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
@jcantrill any objection to this? it takes quite a while to run the full suite (I think about an hour) but we really need be making sure that we are not breaking things.

If this is deemed to take too much time for the a merge check, would it be possible to run a daily full test suite instead? I would just like to make sure that we are not breaking things

**Comment by jcantrill** [comment]
@danmcp do you have concerns about the length of time it takes to run tests? like to we have a restriction on the number of jobs that can be running at once?  Do we have options to say have targeted tests for PR's with maybe an extended suite to run daily or a way to trigger a longer suite manually?

**Comment by danmcp** [comment]
@jcantrill 
> do you have concerns about the length of time it takes to run tests?  like to we have a restriction on the number of jobs that can be running at once? 

We would need to tune for it if you have more than 5 or 6 running at 1 time time.  Otherwise my only concern is that test systems that take longer than an hour are generally loathed by the people that have to use them.


Do we have options to say have targeted tests for PR's with maybe an extended suite to run daily or a way to trigger a longer suite manually?

Yes.  We have _extended jobs that are kicked off after each devenv_ami (which is kicked off after each successful merge).  Or they can also be set to run on a schedule.

**Comment by mwringe** [comment]
+1 to loathing having to use long running test suites, a big part of the problem is that we are spending a crazy amount of time just setting up and configuring the test environment. 

With our current minimal test coverage (eg one smoke test) it would only take me 2 minutes to run it locally, while on the CI it would take half an hour. Is there anyway we can speed up how the test environment works?

**Comment by danmcp** [comment]
@mwringe I've beefed up the instance size (doubled).  Let's see how much that helps.

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
@danmcp @jcantrill Any opinions here? Even with the beefed up machine, it takes about an hour.

I don't personally see it taking an hour as a huge problem from a developer perspective, I can run the full suite locally in about 20 minutes if I am making a lot of changes to how things work and want to make sure it will pass.

**Comment by richm** [comment]
Does the test build or pull images?  If so, is that what takes the longest?

**Comment by mwringe** [comment]
Yes, we need to build our images and it looks like that might be taking up a lot of time. Is there anything we can do here? Potentially use cached images so that we don't have to pull new images each time?

**Comment by richm** [comment]
@mwringe right - we had to do a `docker pull $image` for each of the images we use in the logging test, in order to solve some of the timeout issues.  But what would be really nice is to build a devenv + metrics images ami.  Then when you run the metrics-devenv ami the images are already pre-loaded.  I would like to do this for logging too.

**Comment by jcantrill** [comment]
@mwringe My opinion is if it is not adversely affecting your workflow from a metrics developer perspective, and the CI resources are not blocking any other CI resources, I would leave it as is.

**Comment by mwringe** [comment]
what was the consensus on this? merge, not merge?

**Comment by jcantrill** [comment]
@mwringe my thought is leave as is and fix when/if it becomes an issues...murge....

**Comment by mwringe** [comment]
[merge]

**Pull request merged**
