### PR TITLE
Add support for storing metrics to hostpath.

### PR DESCRIPTION
**Pull request by mwringe**
Adds in support for storing metrics to a directory on the node itself (an alternative option to just using pv, dynamic pv, or pod based storage). Specified using the METRIC_STORAGE deployer parameter.

Makes a few changes to how we handle the Cassandra template. Instead of having 3 very similar templates, we now only have one. This template is modified based on the type of storage being requested.

When adding in new changes for things like resource limits and other configuration options, modifying the templates in this manner will probably have to be done in a  similar way.

Note that this PR does not contain doc updates or a deployer which will exit properly (the post deploy checks will cause a failure). Looking for some discussion before completing the PR.

### CODE REVIEW

**Comment by mwringe** [comment]
@bbguimaraes @jcantrill thoughts on this?

**Comment by jcantrill** [comment]
The works is done so it could be merged; seems reasonable to reduce templates.  I question if this should be done for the deployer instead of directly into the ansible code: https://github.com/openshift/openshift-ansible/pull/2873  Ansible is where deployment is going so it seems this is where we would prefer to make changes, unless there is some urgent request to have this in the master code stream

**Comment by fgiloux** [comment]
This change would be very beneficial, following Apache Cassandra recommendation [1]: "In most cases, Cassandra is designed to provide redundancy via multiple independent, inexpensive servers. For this reason, using NFS or a SAN for data directories is an antipattern and should typically be avoided."
Ideally daemonset with a node selector should be used instead of a replication controller until statefulset is fully supported.

[1] http://cassandra.apache.org/doc/latest/operating/hardware.html#disks

**Comment by jcantrill** [comment]
@fgiloux The question is not whether we should do the change but where.  Our preferred method of installation is to use openshift-ansible so these changes should be addressed there.

**Comment by fgiloux** [comment]
@jcantrill Totally agreed. Thanks for the information. Found the openshift-ansible PR for the records: https://github.com/openshift/openshift-ansible/pull/2873

**Pull request closed without merging**
