### PR TITLE
Hawkular Alerts integration with Logging

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
@gbaufake , could you please try the following scenarios?

- [ ] Current "master" Ansible with images from this PR
- [ ] Images from the Ansible's related changes ([my branch](https://github.com/jpkrohling/openshift-ansible/tree/JPK-HawkularAlertsWithLogging) ).

Script to use for testing:
https://gist.github.com/jpkrohling/ef5999334dc488a838fb45ae459174e9

For the first case, you might want to change the `git clone` line to checkout master (or a previous tag). For both cases, you'll need to change the property `openshift_metrics_image_prefix` to use the images you built yourself.

You can build the images from this repository by running the following command:

```
./hack/build-images.sh --prefix=jpkroehling/origin- --version=dev
```

The first part of the prefix should match your Docker Hub namespace (create an account there if you don't have one yet). Once the images are built locally, push all 4 of them to Docker Hub (`docker login ... ; docker push ...`)

**Comment by jpkrohling** [comment]
cc @lucasponce , @jcantrill

**Comment by mwringe** [comment]
I don't know if we want this for the deployer, the deployer has been deprecated.

Do you have a PR for ansible?

**Comment by jpkrohling** [comment]
The branch is ready, but the PR has not been submitted yet. I believe this PR should be merged before the other, which is why I'm waiting to open the PR for Ansible:
https://github.com/jpkrohling/openshift-ansible/tree/JPK-HawkularAlertsWithLogging

**Comment by jpkrohling** [comment]
@mwringe : what's the best way to document this? Is there a docs repo somewhere that I could fork and change? Is it also required for the dev cut?

**Comment by mwringe** [comment]
@jpkrohling you should submit a PR to https://github.com/openshift/openshift-docs that explains what this is and how to use it.

**Comment by jpkrohling** [comment]
By the way: I'm currently being affected by https://github.com/openshift/origin/issues/14393 , and looks like @gbaufake is as well. During the development, I added `--disablerepo=origin-local-release` to the `yum` command as a workaround, but removed before sending this PR. 

Should we add this option to the `yum` command to the Dockerfiles as part of this PR?

**Comment by gbaufake** [comment]
@jpkrohling 

First Test case 
- Docker images from this pull request (https://hub.docker.com/r/gbaufake/)
- Current Master from Openshift-Ansible 

`fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "daemon_reload": false,
            "enabled": null,
            "masked": null,
            "name": "origin-master",
            "no_block": false,
            "state": "restarted",
            "user": false
        }
    }
}`

`MSG: Unable to restart service origin-master: Job for origin-master.service failed because the control process exited with error code. See "systemctl status origin-master.service" and "journalctl -xe" for details.`


Second Test Case

- Docker images from this pull request (https://hub.docker.com/r/gbaufake/)
- HawkularAlertsWithLogging Branch on @jpkrohling repository  - https://github.com/jpkrohling/openshift-ansible.git . -b JPK-HawkularAlertsWithLogging

- Got this Result:
https://paste.fedoraproject.org/paste/5wa60ViYhvVxtdedcvwYOA

It seems to be ok


Third Case 
-  Following https://github.com/openshift/openshift-ansible#getting-the-correct-version I tested the first case with `release-1.5` branch

**Comment by gbaufake** [comment]
I think we going to need to rebase this branch with `release-1.5` first

**Comment by jpkrohling** [comment]
@jcantrill , @mwringe , the test failures don't seem related to this PR.

Considering that the change is small and non-intrusive, and considering that the failures are properly handled, would you consider merging this for 3.6, or is it too risky? If we can get it for 3.6, do we still have a chance of getting the playbook counterpart merged in time as well?

**Comment by gbaufake** [comment]
@jpkrohling, I will do the a "sanity test" with current master with some modifications on inventory for 1.6 instead of 1.5 

On the `release-1.5`, origin-metrics is working well and it seems to have a "backwards compatibility". 

Best Regards,
Guilherme Baufaker Rêgo

**Comment by mwringe** [comment]
[merge]

**Comment by jpkrohling** [comment]
```
"/bin/test_pull_requests:855:in `test_merge_pull_request': Missing 'Metrics Merge Results:' comment! (RuntimeError)"
```

I don't really understand what this failure is about...

**Comment by mwringe** [comment]
[merge]

**Pull request merged**
