### PR TITLE
Fixes #341 - Remove stores on boot, created from previous runs.

### LINKED ISSUE #341: Cannot use oc debug with Hawkular Metrics
We cannot use oc debug anymore with Hawkular Metrics due to the way the keystores and truststores are setup.

Steps to reproduce:
\# debug the Hawkular Metrics pod
oc debug ${HAWKULAR_METRICS_POD}
\# export the hostname, the default one is too long and will cause Hawkular Metrics to fail
export HOSTNAME=hawkular-metrics-debug
\# start hawkular metrics with its command

/opt/hawkular/scripts/hawkular-metrics-wrapper.sh -b 0.0.0.0 .....

\# notice that Hawkular Metrics starts up properly
\# stop Hawkular Metrics (ctrl-c) and rerun the above command.

notice the following failure:
Converting the PKCS12 keystore into a Java Keystore
keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect
java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at sun.security.tools.keytool.Main.doCommands(Main.java:799)
	at sun.security.tools.keytool.Main.run(Main.java:345)
	at sun.security.tools.keytool.Main.main(Main.java:338)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
	... 7 more

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
We actually have two options: the first is to try to recover the password from the previous runs, probably by inspecting/parsing `${HAWKULAR_METRICS_DIRECTORY}/server.properties`, or remove and start over.

I prefer the first option, as it's simpler and there's really no reason to keep the old stores there, but I'm open to hear arguments in favor of the other option, if there's any.

**Comment by mwringe** [comment]
I think its good to recreate instead of trying to restore.

**Comment by mwringe** [comment]
[merge]

**Comment by jpkrohling** [comment]
Failed because of this: `Branch is Closed for Non-Blocker Bugs`

**Pull request merged**
