### PR TITLE
[BZ 1474099] Improve restart performance and reduce the memory usage

### PR DESCRIPTION
**Pull request by burmanm**
* Adds detection of stale cached definitions
* Reduces the amount of memory used for caching of each object (uses a hashcode instead of object)
* Speeds up initial startup time by fetching all definitions from Hawkular-Metrics in a single call
  * Requires new version of Hawkular-Metrics

### CODE REVIEW

**Comment by mwringe** [comment]
LGTM but this introduces some more CPU pressure and we might want to have the scalability team take a closer look.

**Comment by mwringe** [comment]
[test]

**Comment by mwringe** [comment]
[merge]

**Comment by jsanda** [comment]
[merge]

**Pull request merged**
