### PR TITLE
Added --hostname parameter to route command

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
Without this PR, this is how the route looks like after a `oc cluster up --version=latest --metrics=true`

```
oc get route hawkular-metrics
NAME               HOST/PORT                                           PATH      SERVICES           PORT             TERMINATION
hawkular-metrics   hawkular-metrics-openshift-infra.127.0.0.1.nip.io             hawkular-metrics   https-endpoint   reencrypt
```

And this is the output with this PR applied:

```
oc get route hawkular-metrics
NAME               HOST/PORT                                  PATH      SERVICES           PORT             TERMINATION
hawkular-metrics   metrics-openshift-infra.127.0.0.1.nip.io             hawkular-metrics   https-endpoint   reencrypt
```

This seems to be required: https://github.com/openshift/origin/blob/master/pkg/bootstrap/docker/openshift/metrics.go#L213

I'm just not sure when this started to be a problem, as the linked code seems to be 10 months old already. Has something else recently changed that might have caused this?

**Comment by jpkrohling** [comment]
Tested with:

```
./_output/local/bin/linux/amd64/oc version
oc v3.6.0-alpha.1+9ffceb8-70
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.1+9ffceb8-70
kubernetes v1.5.2+43a9be4
```

**Comment by mwringe** [comment]
Is there a corresponding issue/bugzilla which was opened for this issue?

**Comment by jpkrohling** [comment]
Not that I'm aware of.

**Pull request closed without merging**
